### ISSUE TITLE
Sample App Crashed Clicking on Send Transaction

### ISSUE THREAD

**Issue by jigarfumakiya** [magiclabs/magic-android#24]
Hello Team

I have implemented the sample code provided by the SDK documentation and have replaced the placeholder values with my magic link KEY. However, I have encountered an issue where, after logging in, the app goes to ANR (Application Not Responding) state when attempting to send a transaction, and nothing happens.

I have attempted to resolve this issue by making changes to the relevant method, as shown below, but I have not received any callbacks or indications of progress:

```
  val receipt = web3j.ethSendTransaction(transaction).sendAsync()
            receipt.whenComplete { ethSendTransaction, throwable ->
                if (throwable != null) {
                    Log.e("Error", throwable.toString())
                } else {
                    Log.d("Magic", ethSendTransaction.transactionHash)
                    mainTabActivity.toastAsync("Transaction complete: " + ethSendTransaction.transactionHash)
                }
            }
```

Could you please provide me with some guidance on how to resolve this issue? Any assistance you can provide would be greatly appreciated.

**Comment by Ethella** [comment]
Hey @jigarfumakiya, have you pressed the public address button before calling the sendTransaction? It is a prerequisite as the public address is needed as part of the transaction object.

Lmk if the problem still persists

**Comment by Jigar-zest** [comment]
Hey @Ethella 
I just wanted to let you know that I clicked the "Get Address" button, and the wallet address was generated successfully. However, when I tried to click "Send Transactions," nothing seemed to happen.

https://user-images.githubusercontent.com/103750692/232763783-d3fed8e8-dc65-4fd8-b8fb-c6fd74f37401.mp4

**Comment by jigarfumakiya** [comment]
Hey @Ethella
I just wanted to let you know that I clicked the "Get Address" button, and the wallet address was generated successfully. However, when I tried to click "Send Transactions," nothing seemed to happen.


https://user-images.githubusercontent.com/11865669/232764587-0d49055f-68e1-4b0a-ac77-ba5f4b2e514f.mp4

**Comment by jigarfumakiya** [comment]
Hey @Ethella are you guys able to reproduce the issue?

**Comment by Ariflo** [comment]
Hi @jigarfumakiya Thanks again for bringing this to our attention. We can reproduce the it and are looking into finding a solution to apply to our demo application. 

In the meantime, could you confirm whether or not you see any logs being displayed in `Logcat`? If not, you might need to move [this line](https://github.com/magiclabs/magic-android/blob/main/example/src/main/java/link/magic/DemoApp.kt#L13) above where the Magic object is being instantiated. Let us know what, if any, logs you see being provided.

**Comment by jigarfumakiya** [comment]
Thanks, @Ariflo , I will make the changes and get back to you if it works.
