### ISSUE TITLE
RpcProvider.context memory leak

### ISSUE THREAD

**Issue by kotoMJ** [magiclabs/magic-android#36]
When using LeakCanary tool on the project where is Magic authentication used there is a trouble with **activity context** passing to the `magic.auth.loginWithEmailOTP` or `magic.auth.loginWithSMS`
Starting another activity and finishing current activity (where context of current activity is passed to RpcProvider of current Magic object) causing **LeakCanary alarm about leaking activity's context**.

Any attempts to avoid the leak in my app was unsuccessful. So I tried to apply the LeakCanary on the https://github.com/magiclabs/magic-android/tree/main/example and it's also leaking so we can talk about that case specifically.
Any advice about how to avoid described memory leak is appreciated.

The heap analysis result related to example app is:

 ```
====================================
HEAP ANALYSIS RESULT
====================================
1 APPLICATION LEAKS

References underlined with "~~~" are likely causes.
Learn more at https://squ.re/leaks.

344666 bytes retained by leaking objects
Signature: 6a00f9e7c1406f0b8cf0ad9b71763c2896cc91da
┬───
│ GC Root: System class
│
├─ android.provider.FontsContract class
│    Leaking: NO (DemoApp↓ is not leaking and a class is never leaking)
│    ↓ static FontsContract.sContext
├─ link.magic.DemoApp instance
│    Leaking: NO (Application is a singleton)
│    mBase instance of android.app.ContextImpl
│    ↓ DemoApp.magic
│              ~~~~~
├─ link.magic.android.Magic instance
│    Leaking: UNKNOWN
│    Retaining 3.0 kB in 101 objects
│    ↓ Magic.rpcProvider
│            ~~~~~~~~~~~
├─ link.magic.android.core.provider.RpcProvider instance
│    Leaking: UNKNOWN
│    Retaining 1.9 kB in 67 objects
│    context instance of link.magic.demo.login.MALoginActivity with mDestroyed = true
│    ↓ RpcProvider.context
│                  ~~~~~~~
╰→ link.magic.demo.login.MALoginActivity instance
​     Leaking: YES (ObjectWatcher was watching this because link.magic.demo.login.MALoginActivity received
​     Activity#onDestroy() callback and Activity#mDestroyed is true)
​     Retaining 344.7 kB in 4440 objects
​     key = dd1ffc7f-b2ef-476e-95c7-f60b2f2f4496
​     watchDurationMillis = 38786
​     retainedDurationMillis = 33781
​     mApplication instance of link.magic.DemoApp
​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
====================================


```

**Comment by romin-halltari** [comment]
Thanks for reporting this @kotoMJ, we will look into it and provide an update shortly.

**Comment by romin-halltari** [comment]
Hey @kotoMJ I just merged a PR that resolves the memory leak issue on the demo app. No changes were needed on the SDK level.

I don't know what your implementation looks like, but if this doesn't help, maybe look into implementing a singleton approach:

```
package link.magic

import android.content.Context
import link.magic.android.Magic
import link.magic.android.Magic.Companion.debugEnabled

object MagicInitializer {
    lateinit var magic: Magic

    fun initialize(context: Context, apiKey: String) {
        magic = Magic(context, apiKey)
        debugEnabled = true
    }

    fun destroy() {
        magic = null as Magic
    }
}
```

After initializing the magic instance using `MagicIntializer.initialize`, you can access your `magic` instance through `MagicInitializer.magic`. Before your app is closed, don't forget to call `MagicInitializer.destroy()`. Hope this helps!

**Comment by kotoMJ** [comment]
Hi, @romin-halltari thank you for the very fast reaction 👏 .
I went through to merged PR and the result in the example app is turning 8 leaking objects into 8 unreachable objects. Which is a move forward 👍 

I appreciate your advice related to clearing reference in destroy of the app. Anyway the problem I have seems to be different. It's not an issue when closing the app, but rather when switching the activity.

When talking about issue in my case there is a bit different stack than in the example app. The problem in my case is context of the activity to be passed to the RpcProvider. This will override the applicationContext in WebViewWrapper which allows to showOverlay (overlay is showing with activity context only). When I switch the activity, the context seems to be stuck in the WebView 😞 . I know it's hard to help me with the exact case and I will put a bit more energy and try somehow free up the activity context from the RpcProvider when I'll not need the webView to show anymore. I just thought there might be some way how to improve the RpcProvider to allow resetContext when activity is finishing.
